### ISSUE TITLE
Error calling openapi-diff from build task

### ISSUE THREAD

**Issue by RRaethke** [knom/vsts-swagger-tasks#11]
Hello!

I was trying out the new openapi v3 functionality (thank you for the implementation!) that was just added and got this error when running in my pipeline:

##[error]An error occurred calling openapi-diff{"jse_shortmsg":"ReferenceError: Circular $ref pointer found at d:/a/1/s/#/components/schemas/JToken/items","jse_info":{},"message":"ReferenceError: Circular $ref pointer found at d:/a/1/s/#/components/schemas/JToken/items","code":"OPENAPI_DIFF_DIFF_ERROR"}
##[error]An error occurred calling openapi-diff!
Finishing: Compare swagger specs

I have tried using both the file path and url option for comparison but both result in the same error being thrown

**Comment by knom** [comment]
Thanks @RRaethke !
Can you share the contracts by any chance?

AND have you tried other contracts, that don't include $ref...?

THANKS.

**Comment by RRaethke** [comment]
Without posting 500 examples, here is a sample of one of our schemas, they are all structured the same. We are generating our swagger with swashbuckle.



I have tested it against the petstore example here: https://petstore3.swagger.io/api/v3/openapi.json
Everything seems to be working fine with this one, so it must be a problem on my side.

**Comment by RRaethke** [comment]
@knom 
After further investigation I have found that circular references are not supported by the openapi-diff library that is being used. It is documented here: https://bitbucket.org/atlassian/openapi-diff/src/68a0ebce1ec07f21b8e51a008321208c58eab1d6/docs/OPENAPI3.md

I will attempt to remove the $refs from the spec with a parser before passing them to the build task, thanks for looking into it though!
