### ISSUE TITLE
Swagger v2 compare fails

### ISSUE THREAD

**Issue by LeathelBacon** [knom/vsts-swagger-tasks#12]
Hi Knom,

It would seem like the swagger (2.0) compare between the two URLs prompts an issue for host, although it shouldn't do any compare on host when comparing between two different URL's. This started on recent changes to task.

**]Rule: edit-host, Message Host turned from abc.contoso.com to abc.qa.contoso.com**

I've tried going back to task v1 and still the same issue for swagger diff.

**Comment by knom** [comment]
@LeathelBacon I updated both v1 and v2 of the task to the underlying library swagger-diff v 0.6.0.
That must have included that new rule...

In V1 there's "Swagger-Diff Configuration Override" that you can pass in under "advanced" group.

Taking a look at [swagger-diff docs](https://www.npmjs.com/package/swagger-diff) you could probably override the RULE to ignore it like that..

```
{
  "rules": {
    "edit-host": 0
  }
}
```
