### ISSUE TITLE
Feature Request ==> Notification/Output

### ISSUE THREAD

**Issue by klweddel** [knom/vsts-swagger-tasks#3]
Thanks for the tool, works great but it would be nice if it could dump the results to a file, email or slack sorta notification. We use it for our internal API validation to see if the change would break the apps consuming the API. Hence a naming change may/may not be a breaking change depending if the consuming app was also updated. Hence the notification would allow us to notify all parties that a "non-black box" change was made to the API and all consuming apps need to be reviewed. 
Thanks

**Comment by knom** [comment]
Thanks for the request @klweddel!
I guess the task could output the results to a file -- and you could then use the file for any notification...?

**Comment by knom** [comment]
Would you be willing to implement the "file output" yourself? 
And do a pull request?

Would be the fastest ;-)

**Comment by klweddel** [comment]
We are using an on-premise TFS server. So I ended up using powershell to
call the TFS API endpoints using the BuildId to get the build logs. I was
then able to some string parsing to get just the differences lines in your
log. From there I created a HTML formatted email to send to all the
developers.
