### ISSUE TITLE
Support for 3.0 and above

### ISSUE THREAD

**Issue by LeathelBacon** [knom/vsts-swagger-tasks#7]
Hi,

We are using the Azure DevOps extension. Could you please add support for 3.0 and above?

 ##[error]An error occurred calling swagger-diff{"name":"SyntaxError","message":"http://xyz.com/swagger/v1/swagger.json is not a valid Swagger API definition",

**Comment by knom** [comment]
That is a great idea!
However.. not an easy one, as 2.0 and 3.0 differ and the library that I'm using underneath doesn't support it..

Looking into it..

**Comment by knom** [comment]
@LeathelBacon thanks for your great idea!
I managed to use openapi-diff and build a v2.0 of the task, which has now support for OpenAPI.

Find it in the marketplace under version 2.0

**Comment by LeathelBacon** [comment]
Hi Knom,

Many thanks for this! However, I think the version 2 of extension hasn't been rebuilt and published. Could it be?

**Comment by knom** [comment]
True.. @LeathelBacon 
Still testing it..

If you share with me your AzDO URL I can share the PRIVATE test version with you..
(so you can test it and give feedback, before it goes into the public marketplace)

**Comment by LeathelBacon** [comment]
> True.. @LeathelBacon
> Still testing it..
> 
> If you share with me your AzDO URL I can share the PRIVATE test version with you..
> (so you can test it and give feedback, before it goes into the public marketplace)

That's a great idea. 
dev.azure.com/payoneer

**Comment by knom** [comment]
Great. Just added you..
